### PR TITLE
Feature/bump core dependencies to angular 8

### PR DESCRIPTION
**Pull request by bbortt**
This PR contains the following changes:
* Initial `@angular/cli:^8.0.3` update by @DenisaSurdu
    * Squashed and signed commits into current
* Bumping project dependencies to `@angular/cli:^2.4.0` compatible versions
* Bumping peer dependencies to `@angular/cli:^2.4.0` compatible versions
* Updating `angular.json` with compatible tags
    * `- "architect" + "targets"`

Because of the `scripts`-tag in `package.json` it seems like the primary package manager is `yarn`. Therefore I reconfigured the `angular.json` and removed the `package-lock.json` as well.

### CODE REVIEW

**Comment by bbortt** [comment]
to: @kuhnroyal 
cc: @DenisaSurdu
fixes: #69

**Comment by intellix** [comment]
Good to merge? Angular 9 is almost upon us

**Comment by bbortt** [comment]
>     * polyfills.ts is out of date

no wonder, if nobody merges this within years :D @intellix

**Comment by Roen00** [comment]
Hello, any progress on this issue? What prevents the merge?

**Pull request merged**
