### PR TITLE
accessibility fixes

### LINKED ISSUE #90: Accessible name is not meaningful for Next and Previous elements in year view
Currently, the screen reader announce it as previous and next month instead of previous and next year.

Screenshot 2020-03-26 at 14 32 39

**Expected behavior**
Ensure that accessible name is meaningful for the mentioned elements

### PR DESCRIPTION
**Pull request by DenysVuika**
Provides support for bindable (localizable) aria-label values for Next and Prev buttons.
Correctly displays the aria labels based on the "year" and "month" modes.
Adds missing "role" attributes for buttons.
Fixes the active cell highlight
Update readme formatting and examples.

Fixes #90, #92

### CODE REVIEW

**Comment by bbortt** [comment]
Appreciate.

**Comment by DenysVuika** [comment]
thanks @bbortt, any chances for this PR to land on NPM soon, at least for the 3.x branch?

**Comment by bbortt** [comment]
Already done.. `3.1.0` if I remember it correctly.

**Comment by DenysVuika** [comment]
Oh, that's great thanks! We are trying to get accessibility certification for our application that is using the datetime picker component, so I may be creating more PRs to address a11y bugs.

Thanks for fast responses!

**Pull request merged**
