### PR TITLE
refactor(schematics): add "eslint:recommended" to eslintrc file

### PR DESCRIPTION
**Pull request by naaajii**
should close upon completion #179.

### CODE REVIEW

**Comment by bbortt** [comment]
@Naaajii I appreciate the contribution, but there is some more that needs to be done (see the [action results](https://github.com/kuhnroyal/mat-datetimepicker/actions/runs/4845250888/jobs/8719716738?pr=446)) 😉 this code is kinda messy, if you aren't used to it. let me know if you need any help.

**Comment by naaajii** [comment]
@bbortt thanks for reminding me, I didn't finish this off where. I will defi appreciate if you can provide me some heads up against what should we do ahead, I did run it with `--fix` which only fixed two or three issues, what should go with `no-undef` & bout `no-unused-vars` instead of it omitting errors should it be warnings?

**Comment by bbortt** [comment]
> I did run it with --fix which only fixed two or three issues

I know, it's a shame.. must do almost everything by handwork. that's why I've never started it.

> instead of it omitting errors should it be warnings

that sounds like a good idea - then we would at least be aware of it. and could resolve them one by one.

**Comment by naaajii** [comment]
I have updated the PR!

**Review by bbortt — APPROVED** [review]
would merge this after #453.

**Pull request merged**
