### PR TITLE
Feature/deps and doc

### PR DESCRIPTION
**Pull request by bbortt**
overrides #256.

### CODE REVIEW

**Comment by bbortt** [comment]
@kuhnroyal can you please remove the "need for check node 12 & 14"?

**Comment by bbortt** [comment]
> @kuhnroyal can you please remove the "need for check node 12 & 14"?

@kuhnroyal, please? ;)

**Comment by kuhnroyal** [comment]
> > @kuhnroyal can you please remove the "need for check node 12 & 14"?
> 
> @kuhnroyal, please? ;)

Done! Sry, totally missed that comment.

**Comment by bbortt** [comment]
no problem @kuhnroyal, thanks very much.

**Pull request merged**
