### PR TITLE
propagate accessibility fixes from 3.x to master

### PR DESCRIPTION
**Pull request by DenysVuika**
This is a cherry-picked range of accessibility fixes that were merged to 3.x branch

### CODE REVIEW

**Comment by DenysVuika** [comment]
I have rebased the PR

**Comment by bbortt** [comment]
I cannot disable the `Require signed commits` for master. @kuhnroyal would have to do this. Any chance you can sign (GPG signature) those commits @DenysVuika? I could squash them for you otherwise.

**Comment by DenysVuika** [comment]
Sorry, I don't have GPG for commits at this point.

**Comment by bbortt** [comment]
Closing in favor of #98 .

**Pull request closed without merging**
