### PR TITLE
chore(deps): weekly dependency scan

### PR DESCRIPTION
**Pull request by bbortt**

### CODE REVIEW

**Review by kuhnroyal — DISMISSED** [review]

**Comment by bbortt** [comment]
@kuhnroyal that's odd.. why don't the actions run on my fork? :(

**Comment by kuhnroyal** [comment]
I dunno tbh, wonder if we reached some limit

**Comment by bbortt** [comment]
ah, maybe you need to tick something in the settings (see first image)? https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/.

**Comment by kuhnroyal** [comment]
Dunno, I force-pushed over your commit and now it seems to have triggered, maybe some service was down, had this happen before.

**Comment by bbortt** [comment]
> ah, maybe you need to tick something in the settings (see first image)? https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/.

never mind, that's for private repositories.

**Review by kuhnroyal — APPROVED** [review]

**Comment by kuhnroyal** [comment]
I enabled auto merge

**Pull request merged**
