### PR TITLE
feat: update Angular from v16 to v17

### PR DESCRIPTION
**Pull request by Tweniee**
Issue: #503

### CODE REVIEW

**Comment by bbortt** [comment]
sick! please check that the builds pass. also, you need to type the commit such that the convention introduces a breaking change. see the [conventional commit summary](https://www.conventionalcommits.org/en/v1.0.0/#summary) for more information.

**Review by bbortt — CHANGES_REQUESTED** [review]
sick! please check that the builds pass (`package-lock.json` not aligned with `package.json`). also, you need to type the commit such that the convention introduces a breaking change. see the [conventional commit summary](https://www.conventionalcommits.org/en/v1.0.0/#summary) for more information.

**Comment by Tweniee** [comment]
@bbortt  hope these changes works fine

**Comment by kodeaben** [comment]
Hi :) 
Is this PR getting merged soon?

**Comment by bbortt** [comment]
https://github.com/kuhnroyal/mat-datetimepicker/releases/tag/v13.0.0

**Comment by Tweniee** [comment]
Thanks

**Pull request closed without merging**
