### PR TITLE
Angular 9 and Ivy

### PR DESCRIPTION
**Pull request by kamilkisiela**

### CODE REVIEW

**Comment by bbortt** [comment]
I cannot merge this if the build fails. Actually I hadn't even time to look into the `@angular/v8` build.. and please sign your commits ;)

**Comment by ellavas** [comment]
Any news on this PR ?
The package is currently incompatible with Angular 9, so could you please have a look ?

**Comment by kamilkisiela** [comment]
I won't touch it

**Comment by bbortt** [comment]
Will close this in favour of #84 .

**Pull request closed without merging**
