### PR TITLE
5.x - review and fix the multiple UTZ conversion

### PR DESCRIPTION
**Pull request by ssdhaliwal**
Trying to fix the UTZ conversion happening when useUtc is set to true.

### CODE REVIEW

**Comment by bbortt** [comment]
hi @ssdhaliwal. it seems to me, you did forget to add your commits? as for now, you're just adding old versions into our main branch. the `5.x` branch is for angular 10.

**Comment by bbortt** [comment]
label: `stale`

**Comment by joelcoxokc** [comment]
Any progress on this. I am stuck using a different project until this is fixed?

**Comment by bbortt** [comment]
@joelcoxokc this PR doesn't even include changes and is marked as `stale`. so no, no progress so far. I don't have time for this either, sorry. happy to accept another PR if you look into it.

**Pull request closed without merging**
