### PR TITLE
fix:- select date-time from keyboard

### PR DESCRIPTION
**Pull request by dhrn**
This allows the user to select date-time from the keyboard.

### CODE REVIEW

**Review by bbortt — APPROVED** [review]
/lgtm

**Comment by dhrn** [comment]
what should we user selects the same date-time. currently, it is not closing

**Comment by dhrn** [comment]
@bbortt when will be published?

**Comment by bbortt** [comment]
@dhrn sorry, was pretty busy. I will read it through and publish it by tonight.

**Comment by dhrn** [comment]
thanks

**Review by bbortt — APPROVED** [review]
seems fine, thx.

**Comment by bbortt** [comment]
you didn't sign your commits, so I squashed them: https://github.com/kuhnroyal/mat-datetimepicker/commit/6cb7ee39f016815b76ada7880563572aedcced01.
released in version `5.1.1`.

**Pull request closed without merging**
